version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    entrypoint: "npm run start"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    command: ["npm","run","test"]